### ISSUE TITLE
error while building CRKBD

### ISSUE THREAD

**Issue by decadenzio** [drcforbin/keyboards#1]
Hi, I'm trying out your crkbd firmware but when compiling i get this error:

`root@kali:~/Github/qmk_firmware# qmk compile -kb crkbd -km experimental
Ψ Compiling keymap with make crkbd:experimental

QMK Firmware 0.7.140
Making crkbd/rev1 with keymap experimental

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/crkbd/keymaps/experimental/oled.c                                             keyboards/crkbd/keymaps/experimental/oled.c: In function ‘render_frame’:
keyboards/crkbd/keymaps/experimental/oled.c:176:9: error: implicit declaration of function ‘oled_write_raw_byte’ [-Werror=implicit-function-declaration]
         oled_write_raw_byte(line1[i], ROW_1 + i);
         ^
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [tmk_core/rules.mk:380: .build/obj_crkbd_rev1_experimental/oled.o] Error 1
Make finished with errors
make: *** [Makefile:579: crkbd:experimental] Error 1
`

Any idea on how to fix?

**Comment by drcforbin** [comment]
Do you have `OLED_DRIVER_ENABLE` defined in your `rules.mk`? The `#include QMK_FIRMWARE` should bring in the `oled_driver.h` if so.

**Comment by decadenzio** [comment]
yes i have `OLED_DRIVER_ENABLE = yes` in my `rules.mk` . I don't understand where I should have `#include QMK_FIRMWARE`.

**Comment by drcforbin** [comment]
It's the first line at the top of my `oled.c`. That `#include`, along with the rules var should bring in the header for it. The function was added pretty recently, is it possible your QMK version is older than 0.8.18 (early March)?

**Comment by decadenzio** [comment]
resolved, updating the QMK version resolved the issue, thanks!
